- hosts: windows
  gather_facts: no
  tasks:
  - name: set dns server
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 192.168.0.4

  - win_domain_membership:
      dns_domain_name: ansible.azure
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: "{{ ad_join_user }}"
      domain_admin_password: "{{ ad_join_password }}"
      #domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

