---

- hosts: all
  tasks:
  - name: create partition
    win_partition:
      drive_letter: G
      disk_number: 2
      partition_size: -1

  - name: format partition
    win_format:
      drive_letter: G
      new_label: Data
      file_system: ntfs

