---

- name: add nodes
  bigip_node:
    server: "{{ public_ip }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    host: "{{ hostvars[item]['public_ip'] }}"
    name: "{{ hostvars[item]['inventory_hostname'] }}"
    validate_certs: "no"
  with_items: "{{ groups.windows }}"
  register: result
  until: result is succeeded
  retries: 30
  delay: 10

- name: create pool
  bigip_pool:
    server: "{{ public_ip }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_http_pool"
    lb_method: "round-robin"
    monitors: "/Common/http"
    monitor_type: "and_list"
    validate_certs: "no"
  run_once: true

- name: add nodes to pool
  bigip_pool_member:
    server: "{{ public_ip }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    state: "present"
    host: "{{ hostvars[item]['public_ip'] }}"
    name: "{{ hostvars[item]['inventory_hostname'] }}"
    port: "80"
    pool: "ansible_http_pool"
    validate_certs: "no"
  with_items: "{{ groups.windows }}"

- name: add virtual server
  bigip_virtual_server:
    server: "{{ public_ip }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_virtual_server"
    destination: "{{ private_ip }}"
    port: "443"
    enabled_vlans: "all"
    all_profiles: ['http','clientssl','oneconnect']
    pool: "ansible_http_pool"
    snat: "Automap"
    validate_certs: "no"
