---

- name: add nodes
  bigip_node:
    server: "{{ hostvars[item]['public_ip'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    host: "{{ public_ip }}"
    name: "{{ public_ip }}"
    validate_certs: "no"
  with_items: "{{ groups.type_f5 | first }}"

- name: create pool
  bigip_pool:
    server: "{{ hostvars[item]['public_ip'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_http_pool"
    lb_method: "round-robin"
    monitors: "/Common/http"
    monitor_type: "and_list"
    validate_certs: "no"
  with_items: "{{ groups.type_f5 | first }}"
  run_once: true

- name: add nodes to pool
  bigip_pool_member:
    server: "{{ hostvars[item]['public_ip'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    state: "present"
    name: "{{ public_ip }}"
    host: "{{ public_ip }}"
    port: "80"
    pool: "ansible_http_pool"
    validate_certs: "no"
  with_items: "{{ groups.type_f5 | first }}"

- name: add virtual server
  bigip_virtual_server:
    server: "{{ hostvars[item]['public_ip'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_virtual_server"
    destination: "{{ hostvars[item]['private_ip'] }}"
    port: "443"
    enabled_vlans: "all"
    all_profiles: ['http','clientssl','oneconnect']
    pool: "ansible_http_pool"
    snat: "Automap"
    validate_certs: "no"
  with_items: "{{ groups.type_f5 | first }}"
  run_once: true
