---

- name: Create virtual network
  azure_rm_virtualnetwork:
    name: "{{ az_network_name }}"
    resource_group: "{{ az_rg_name }}"
    address_prefixes_cidr:
      - "{{ az_network_cidr }}"

- name: Create subnet
  azure_rm_subnet:
    name: "{{ az_network_name }}-subnet"
    virtual_network_name: "{{ az_network_name }}"
    resource_group: "{{ az_rg_name }}"
    address_prefix_cidr: "{{ az_network_cidr }}"

- name: Create security group
  azure_rm_securitygroup:
    resource_group: "{{ az_rg_name }}"
    name: ansible-demo-sg
    rules:
      - name: ssh
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: web
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 102
        direction: Inbound
      - name: winrm
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 103
        direction: Inbound
      - name: rdp
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 104
        direction: Inbound
