---

- name: remove default web site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: create directory for dotnet website
  win_file:
    path: C:\webapp
    state: directory

- name: copy app across
  win_copy:
    src: webapp.zip
    dest: C:\Temp\webapp.zip

- name: unzip file
  win_unzip:
    src: C:\Temp\webapp.zip
    dest: C:\webapp


