---

- name: remove default web site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: create directory for dotnet website
  win_file:
    path: C:\webapp
    state: directory

- name: copy app across
  win_copy:
    src: webapp.zip
    dest: C:\Temp\webapp.zip

- name: unzip file
  win_unzip:
    src: C:\Temp\webapp.zip
    dest: C:\webapp

- name: install iis
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: download dotnet core runtime
  win_get_url: 
    url: https://download.visualstudio.microsoft.com/download/pr/a021d9b2-8585-473c-a8d1-011717383ad7/819dbf76040767ed1a49d6c7c5681b8a/aspnetcore-runtime-2.2.6-win-x64.exe
    dest: C:\Temp

- name: install dotnet core runtime
  win_package:
    path: C:\Temp\aspnetcore-runtime-2.2.6-win-x64.exe
    state: present
