---

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ az_rg_name }}"
    allocation_method: Static
    name: "{{ az_vm_name }}-public"
  register: public_ip

- name: Create VM nic
  azure_rm_networkinterface:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_vm_name }}-nic"
    virtual_network: "{{ az_network_name }}"
    subnet: "{{ az_network_name }}-subnet"
    security_group: ansible-demo-sg
    ip_configurations:
      - name: ipconfig1
        primary: True
        public_ip_address_name: "{{ az_vm_name }}-public"
        load_balancer_backend_address_pools:
        - name: backendaddrpool0
          load_balancer: ansible-loadbalancer

- name: Prepare random postfix
  set_fact:
    rpfx: "{{ 100000 | random }}"
  run_once: yes

- name: provision new Azure virtual host
  azure_rm_virtualmachine:
    admin_username: '{{ az_vm_admin_user }}'
    admin_password: "{{ az_vm_admin_password }}"
    availability_set: ansible-availabilityset
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2016-Datacenter
      version: latest
    name: "{{ az_vm_name }}"
    resource_group: "{{ az_rg_name }}"
    state: present
    vm_size: "{{ az_vm_size }}"
    network_interfaces: "{{ az_vm_name }}-nic"

- name: create Azure vm extension to enable HTTPS WinRM listener
  azure_rm_virtualmachine_extension:
    name: winrm-extension
    resource_group: "{{ az_rg_name }}"
    virtual_machine_name: "{{ az_vm_name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
    auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
    timeout: 600
