---

- name: Install IIS (Web-Server and Web-Common-Http)
  win_feature:
    name:
    - Web-Server
    - Web-Common-Http
    state: present
  register: result
  until: result is succeeded
  retries: 30
  delay: 10



- name: default-website-index
  win_template:
    src: templates/index.html.j2
    dest: "C:\\inetpub\\wwwroot\\index.html"
